apiVersion: v1

kind: Service

metadata:

  name: tomcat-service-rvenigalla

  namespace: tomcat

spec:

  type: LoadBalancer

  selector:

    app: tomcat

  ports:

    - port: 8080

      protocol: TCP

      targetPort: 8080


---

apiVersion: apps/v1                          

kind: Deployment

metadata:

  name: tomcat-deployment-rvenigalla

  namespace: tomcat

spec:

  replicas: 1

  selector:

    matchLabels:

      app: tomcat

  template:

    metadata:

      labels:

        app: tomcat

    spec:

      containers:

        - name: tomcat-container-rvenigalla

          image: rvenigallaacrtest.azurecr.io/samplewebapps:latest

          ports:

            - containerPort: 8080